### ISSUE TITLE
Batch Forwarding while Testing

### ISSUE THREAD

**Issue by PhucNDA** [bytedance/OmniScient-Model#3]
Hi, thanks for the significant work.

I have run through the code, it works perfectly. However, there are a lot of segmentation masks on 1 image making the designed testing script run tremendously slow. I have a skim through the training script, it seems like OSM only support batch (1 image, 1 mask) forwarding.  **I don't know whether the model support (1 image, n masks) forwarding test.** 

Thanks alot for significant work OSM.

PhucNDA.

**Comment by cornettoyu** [comment]
Hi PhucNDA,

Thanks for your interests in our work.

Current code does not support batch forwarding during inference. It can be supported by repeating the pixel features and performing a batch forwarding in MaskQFormer. As all input sequence have the length, the batch forwarding in LLM part is also straightforward. I will update the code once I got time, if you would like to implement it yourself and encounter any problem, feel free to let me know as well :)

Best,
